# service.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworldapi
  name: helloworldapi
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: helloworldapi
  type: LoadBalancer

